<?php

return [
    'justification_technical_hemodialysis' => "PACIENTE COM INJÚRIA RENAL NECESSITA TERAPIA DIALÍTICA DE URGÊNCIA POR TEMPO INDETERMINADO. A AUSÊNCIA DESTE TRATAMENTO TRAZ RISCO DE ÓBITO AO PACIENTE. SOLICITO 3 SESSÕES DE HEMODIÁLISE.",
    'justification_technical_dialysys' => "PACIENTE COM INJÚRIA RENAL NECESSITA TERAPIA DIALÍTICA DE URGÊNCIA POR TEMPO INDETERMINADO. A AUSÊNCIA DESTE TRATAMENTO TRAZ RISCO DE ÓBITO AO PACIENTE. SOLICITO 3 SESSÕES DE DIÁLISE PERITONEAL.",
    'justification_technical_catheter' => "PACIENTE COM INJÚRIA RENAL NECESSITA CATETER DE HEMODIÁLISE PARA REALIZAR TERAPIA DIALÍTICA DE URGÊNCIA.",
];
